version: 2.1

jobs:
  build-frontend: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Build frontend 
          command: |
            cd frontend 
            npm install 
            npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Build backend 
          command: |
            cd backend
            npm login 
            npm install
            npm run build

workflows:
  build-project:
    jobs:
      - build-frontend
      - build-backend

